### ðŸŸ¦ Importing Libraries

In [1]:
import pandas as pd
import os

### ðŸŸ¦ Scrutinizing & Editing Data

In [2]:
data = pd.read_csv("https://raw.githubusercontent.com/Alireza-Esp/VFCPM/refs/heads/main/Data/data.csv")

In [3]:
data

,Model year,Make,Model,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km),CO2 rating,Smog rating
0,1995,Acura,Integra,Subcompact,1.8,4,A4,X,11.6,8.3,10.1,28,232,NaN,NaN
1,1995,Acura,Integra,Subcompact,1.8,4,M5,X,11.0,8.3,9.8,29,225,NaN,NaN
2,1995,Acura,Integra GS-R,Subcompact,1.8,4,M5,Z,10.8,8.3,9.7,29,223,NaN,NaN
3,1995,Acura,Legend,Compact,3.2,6,A4,Z,14.2,10.5,12.5,23,288,NaN,NaN
4,1995,Acura,Legend Coupe,Compact,3.2,6,A4,Z,14.6,11.0,13.0,22,299,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28450,2025,Volvo,V60 CC B5 AWD,Station wagon: Small,2.0,4,AS8,Z,9.7,7.5,8.7,32,205,5.0,4.0
28451,2025,Volvo,V90 CC B6 AWD,Station wagon: Mid-size,2.0,4,AS8,Z,10.7,8.1,9.5,30,223,5.0,6.0
28452,2025,Volvo,XC40 B5 AWD,Sport utility vehicle: Small,2.0,4,AS8,Z,10.1,7.8,9.1,31,213,5.0,4.0
28453,2025,Volvo,XC60 B5 AWD,Sport utility vehicle: Small,2.0,4,AS8,Z,10.0,7.8,9.0,31,212,5.0,6.0
28454,2025,Volvo,XC90 B6 AWD,Sport utility vehicle: Standard,2.0,4,AS8,Z,11.5,9.0,10.4,27,244,5.0,6.0

ðŸ”· About 28000 sample

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28455 entries, 0 to 28454
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Model year            28455 non-null  int64
 1   Make                  28455 non-null  object
 2   Model                 28455 non-null  object
 3   Vehicle class         28455 non-null  object
 4   Engine size (L)       28455 non-null  float64
 5   Cylinders             28455 non-null  int64
 6   Transmission          28455 non-null  object
 7   Fuel type             28455 non-null  object
 8   City (L/100 km)       28455 non-null  float64
 9   Highway (L/100 km)    28455 non-null  float64
 10  Combined (L/100 km)   28455 non-null  float64
 11  Combined (mpg)        28455 non-null  int64
 12  CO2 emissions (g/km)  28455 non-null  int64
 13  CO2 rating            9474 non-null   float64
 14  Smog rating           8368 non-null   float64
dtypes: float64(6), int64(4), object(5)
memory usage: 3.3+ MB

ðŸ”· The columns "CO2 rating" and "Smog rating" have about 30% NULL values. deleting them...

In [5]:
data.drop(columns=["CO2 rating", "Smog rating"], inplace=True)

In [6]:
data

,Model year,Make,Model,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km)
0,1995,Acura,Integra,Subcompact,1.8,4,A4,X,11.6,8.3,10.1,28,232
1,1995,Acura,Integra,Subcompact,1.8,4,M5,X,11.0,8.3,9.8,29,225
2,1995,Acura,Integra GS-R,Subcompact,1.8,4,M5,Z,10.8,8.3,9.7,29,223
3,1995,Acura,Legend,Compact,3.2,6,A4,Z,14.2,10.5,12.5,23,288
4,1995,Acura,Legend Coupe,Compact,3.2,6,A4,Z,14.6,11.0,13.0,22,299
...,...,...,...,...,...,...,...,...,...,...,...,...,...
28450,2025,Volvo,V60 CC B5 AWD,Station wagon: Small,2.0,4,AS8,Z,9.7,7.5,8.7,32,205
28451,2025,Volvo,V90 CC B6 AWD,Station wagon: Mid-size,2.0,4,AS8,Z,10.7,8.1,9.5,30,223
28452,2025,Volvo,XC40 B5 AWD,Sport utility vehicle: Small,2.0,4,AS8,Z,10.1,7.8,9.1,31,213
28453,2025,Volvo,XC60 B5 AWD,Sport utility vehicle: Small,2.0,4,AS8,Z,10.0,7.8,9.0,31,212
28454,2025,Volvo,XC90 B6 AWD,Sport utility vehicle: Standard,2.0,4,AS8,Z,11.5,9.0,10.4,27,244

In [7]:
data["Model year"].value_counts().to_dict()

{2015: 1128,
 2016: 1106,
 2009: 1096,
 2012: 1091,
 2011: 1085,
 2018: 1083,
 2013: 1082,
 2008: 1079,
 2014: 1068,
 2017: 1058,
 2019: 1056,
 2007: 1043,
 2010: 1030,
 2005: 1019,
 2022: 976,
 2020: 975,
 2021: 970,
 2006: 968,
 2004: 898,
 2023: 840,
 1995: 839,
 2003: 820,
 2024: 768,
 2002: 740,
 1996: 698,
 1999: 688,
 2001: 679,
 1997: 658,
 2025: 642,
 2000: 638,
 1998: 634}

ðŸ”· The column "Model year" has no problem...

In [8]:
data["Make"].value_counts().to_dict()

{'Chevrolet': 2659,
 'Ford': 2300,
 'BMW': 1769,
 'GMC': 1708,
 'Mercedes-Benz': 1512,
 'Toyota': 1339,
 'Dodge': 1267,
 'Porsche': 1121,
 'Audi': 999,
 'Volkswagen': 945,
 'Nissan': 939,
 'Mazda': 801,
 'Honda': 706,
 'Hyundai': 685,
 'Jeep': 671,
 'Subaru': 642,
 'Volvo': 626,
 'Kia': 593,
 'Lexus': 566,
 'Cadillac': 535,
 'Chrysler': 507,
 'MINI': 459,
 'Jaguar': 436,
 'Pontiac': 390,
 'Buick': 344,
 'Mitsubishi': 340,
 'Acura': 328,
 'Infiniti': 317,
 'Land Rover': 280,
 'Suzuki': 260,
 'Lincoln': 257,
 'Saab': 252,
 'Saturn': 216,
 'Bentley': 173,
 'Ram': 171,
 'Maserati': 161,
 'Rolls-Royce': 140,
 'Lamborghini': 123,
 'Aston Martin': 121,
 'Ferrari': 99,
 'Plymouth': 88,
 'FIAT': 86,
 'Oldsmobile': 79,
 'Genesis': 70,
 'Alfa Romeo': 62,
 'Mercury': 57,
 'Isuzu': 47,
 'Scion': 44,
 'Eagle': 41,
 'Daewoo': 41,
 'smart': 22,
 'Hummer': 21,
 'Geo': 19,
 'Bugatti': 17,
 'SRT': 4}

ðŸ”· SRT is subcategory of Dodge.

In [9]:
data.loc[data["Make"] == "SRT", "Make"] = "Dodge"

In [10]:
data["Model"].value_counts().to_dict()

{'Mustang': 139,
 'F-150': 110,
 'Jetta': 108,
 'F-150 4X4': 101,
 'Ranger': 88,
 'Corolla': 88,
 'Sierra': 86,
 'Silverado': 86,
 'Silverado 4WD': 82,
 'Sierra 4WD': 82,
 'Camaro': 81,
 'Sentra': 76,
 'F-150 FFV': 76,
 'Camry': 74,
 'Accord': 73,
 'Ram 1500': 73,
 'Elantra': 71,
 'Tacoma': 71,
 'A4 quattro': 71,
 'K1500 Sierra 4X4': 71,
 'Altima': 70,
 'C1500 Sierra': 70,
 'Dakota': 69,
 'Passat': 68,
 'F-150 FFV 4X4': 66,
 'Colorado': 63,
 'Canyon': 63,
 'Malibu': 63,
 'Frontier': 62,
 'Dakota 4X4': 62,
 'Sonata': 61,
 'Corvette': 58,
 'Legacy AWD': 56,
 'Accent': 56,
 'Grand Caravan': 51,
 'Escape': 50,
 'Tacoma 4WD': 50,
 'Versa': 50,
 'Ranger 4X4': 50,
 'A6 quattro': 50,
 'Compass': 50,
 'Impreza AWD': 48,
 'Civic': 48,
 'Impala': 47,
 'Grand Cherokee 4X4': 47,
 'Tundra': 47,
 'Lancer': 47,
 'Forester AWD': 47,
 'CTS': 46,
 'Rio': 46,
 'Forte': 45,
 'Mazda6': 45,
 '911 Carrera': 44,
 'Fusion': 43,
 'Boxster': 43,
 'Sunfire': 43,
 'Patriot': 42,
 'Cavalier': 42,
 'Tacoma 4X4': 42,
 'Golf': 42,
 'Equinox AWD': 41,
 'Maxima': 41,
 'A4': 41,
 'Sportage': 41,
 'Soul': 41,
 'Cooper Convertible': 40,
 'Challenger': 39,
 'Edge AWD': 39,
 'Cherokee': 39,
 'Eclipse': 39,
 'Tucson': 39,
 'Passat Wagon': 39,
 'Regal': 38,
 'Equinox': 38,
 'New Beetle': 38,
 'Canyon 4WD': 38,
 'Ram 1500 4X4': 38,
 'Cooper S Convertible': 38,
 'Colorado 4WD': 38,
 'MX-5': 37,
 'Sebring': 37,
 'Focus': 37,
 'Santa Fe': 37,
 'TJ 4X4': 37,
 'C1500 Silverado': 37,
 'Tiburon': 37,
 'Yukon 4WD': 36,
 'Outback AWD': 36,
 'K1500 Silverado 4X4': 36,
 'Fit': 36,
 'Mazda3': 36,
 'GTI': 35,
 'Tahoe 4WD': 35,
 'E150 Van': 35,
 'Sierra FFV': 34,
 'Silverado FFV': 34,
 'Boxster S': 34,
 'Terrain AWD': 34,
 'Compass 4X4': 34,
 'Yukon XL': 34,
 'Yukon XL 4WD': 34,
 '911 Turbo': 34,
 'Grand Caravan FFV': 34,
 'Mustang Convertible': 33,
 'Corolla Matrix': 33,
 '626': 32,
 'Eclipse Spyder': 32,
 'Charger': 32,
 'Caravan': 32,
 'Suburban': 32,
 '911 Carrera 4': 32,
 'Suburban 4WD': 32,
 '4Runner 4X4': 32,
 '911 Carrera 4S': 32,
 'Tahoe': 31,
 'Grand Am': 31,
 'Explorer 4X4': 31,
 'Yukon': 31,
 'Civic Sedan': 31,
 'Terrain': 31,
 'Sienna': 31,
 '911 Carrera Cabriolet': 30,
 'Escape AWD': 30,
 'Focus FFV': 30,
 'Celica': 30,
 'Protege': 30,
 '911 Carrera S Cabriolet': 30,
 'CR-V': 30,
 '911 Carrera S': 30,
 'B4000 4X4': 30,
 'Odyssey': 30,
 'E150 Club Wagon': 30,
 'Charger FFV': 30,
 'Forte 5': 29,
 'Sebring Convertible': 29,
 'Avenger': 29,
 '911 Carrera 4S Cabriolet': 28,
 'Camaro SS': 28,
 'Forte Koup': 28,
 'Firebird': 28,
 'Magentis': 28,
 'Neon': 28,
 'Impreza Wagon AWD': 28,
 '911 Carrera 4 Cabriolet': 28,
 'S10': 28,
 'HHR': 28,
 'Charger (MDS)': 28,
 'Expedition 4X4': 28,
 'Outlander 4WD': 27,
 'Cayenne': 27,
 'B3000': 27,
 'Sonic 5': 27,
 'Sonic': 27,
 'Civic Hatchback': 27,
 'C1500': 27,
 'TSX': 27,
 'Tundra 4WD': 27,
 'Ram 2500 Van': 27,
 'K1500 4X4': 27,
 'RAV4': 26,
 'Silverado 4WD FFV': 26,
 'Sierra 4WD FFV': 26,
 'Grand Prix': 26,
 'Explorer AWD': 26,
 'A4 Avant quattro': 26,
 'Cruze': 26,
 'Pathfinder 4X4': 26,
 '300': 26,
 'Cherokee 4X4': 26,
 'Avalon': 26,
 'TT Coupe quattro': 26,
 'Acadia AWD': 26,
 'NSX': 26,
 'Taurus': 26,
 'Ram 1500 Van': 26,
 'Sorento AWD': 25,
 'Canyon Crew Cab': 25,
 'B4000': 25,
 'Yaris': 25,
 'Mazda3 4-Door': 25,
 'Continental GT': 25,
 'A8L': 25,
 'Colorado Crew Cab': 25,
 'S4': 25,
 'Frontier 4WD': 25,
 'Intrepid': 24,
 'Mazda3 5-Door': 24,
 'Vue': 24,
 'Beetle': 24,
 'Cayman': 24,
 '911 Turbo Cabriolet': 24,
 'C2500 Sierra': 24,
 'BRZ': 24,
 'Pilot AWD': 24,
 'Monte Carlo': 24,
 'ATS': 24,
 'Camaro ZL1': 24,
 'RVR 4WD': 24,
 'Acadia': 24,
 'Explorer': 24,
 'Tribute': 24,
 'Accord Coupe': 24,
 'Edge': 23,
 'TT Roadster quattro': 23,
 'Camry Solara': 23,
 'RVR': 23,
 'Golf GTI': 23,
 'SRX AWD': 23,
 'Patriot 4X4': 23,
 'Elantra GT': 23,
 'Murano AWD': 22,
 'Prius': 22,
 'New Beetle Convertible': 22,
 'Liberty 4X4': 22,
 'M3': 22,
 'Phantom': 22,
 'Cooper': 22,
 'A3': 22,
 'Voyager': 22,
 'MX-5 Miata': 22,
 'Lancer Sportback': 22,
 'Z3': 22,
 'Cayman S': 22,
 '911 Targa 4S': 22,
 'RX 350 AWD': 22,
 '370Z Roadster': 22,
 'John Cooper Works Convertible': 22,
 'Cooper S Countryman ALL4': 22,
 'Tracker Convertible 4X4': 22,
 'E250 Van': 22,
 'Optima': 22,
 'Colorado 4X4': 21,
 'SRX': 21,
 'CR-V AWD': 21,
 'G6': 21,
 'Sorento': 21,
 'Sequoia 4WD': 21,
 'Challenger (MDS)': 21,
 'Canyon 4X4': 21,
 'Cayenne S': 21,
 'G15/G25 Savana Cargo': 21,
 'Tiguan': 21,
 'B2300': 21,
 'K1500 Yukon 4X4': 21,
 'Grand Voyager': 21,
 'Altima Coupe': 21,
 'Q7': 21,
 'G80 AWD': 21,
 'Crosstrek AWD': 21,
 'Taurus FFV': 21,
 'Wrangler 4X4': 21,
 'Sportage AWD': 21,
 'Mirage': 21,
 'Highlander': 21,
 'PT Cruiser': 21,
 'G15/G25 Chevy Van': 21,
 'WRX AWD': 21,
 'X-TYPE': 20,
 'Santa Fe AWD': 20,
 'Cooper 3 Door': 20,
 'Rogue': 20,
 'R8 Spyder': 20,
 'Mystique': 20,
 'Genesis Coupe': 20,
 'Contour': 20,
 '320i': 20,
 'Rogue AWD': 20,
 'Formula': 20,
 'Mazda3 5-Door (SIL)': 20,
 'Quest': 20,
 'Vibe': 20,
 '370Z': 20,
 'Cooper 5 Door': 20,
 'Cooper S Clubman': 20,
 'Spark': 20,
 'Mazda5': 20,
 'M6 Cabriolet': 20,
 'Touareg': 20,
 'Cooper S 3 Door': 20,
 'Cooper S 5 Door': 20,
 'R8': 20,
 'X5': 20,
 'V8 Vantage': 20,
 'S15 Sonoma': 20,
 'HHR Panel': 20,
 'CTS AWD': 20,
 'Caliber': 19,
 'Rondo': 19,
 'Cayenne Turbo': 19,
 'ES 350': 19,
 'F-250': 19,
 'LS': 19,
 'Durango 4X4': 19,
 'A8': 19,
 'Express 2500 Passenger': 19,
 'Savana 2500 Passenger': 19,
 'Sedona': 19,
 '4Runner 4WD': 19,
 'M5': 19,
 'Cobalt': 19,
 'Durango AWD': 19,
 'Civic Coupe': 19,
 '911 Targa 4': 19,
 'Jetta TDI Diesel': 19,
 'Accord Sedan': 19,
 'Trax': 19,
 'MKZ AWD': 18,
 'John Cooper Works Countryman ALL4': 18,
 'Town & Country': 18,
 'Impala FFV': 18,
 'Wrangler JL Unlimited 4X4': 18,
 'Concorde': 18,
 'Jetta GLI': 18,
 'Firefly': 18,
 'Cooper Clubman': 18,
 'Ram 2500 Wagon': 18,
 'Fiesta': 18,
 'Metro': 18,
 'Grand Marquis': 18,
 '300 AWD': 18,
 'Enclave AWD': 18,
 'Tucson AWD': 18,
 'Frontier V6 4X4': 18,
 'C2500': 18,
 'Challenger SRT Hellcat': 18,
 'A5 quattro': 18,
 'Sienna AWD': 18,
 '300 FFV': 18,
 '530i': 18,
 'RAV4 4X4': 18,
 'Journey FFV': 18,
 'Escalade AWD': 17,
 'Express 3500 Passenger': 17,
 'K1500 Tahoe 4X4': 17,
 'Savana 3500 Passenger': 17,
 'Flying Spur': 17,
 'Alero': 17,
 'CX-5': 17,
 'Tercel': 17,
 'Traverse AWD': 17,
 'SLK 350': 17,
 'Cherokee 4X4 Active Drive I': 17,
 'CSX': 17,
 'C1500 Yukon': 17,
 'Sierra 4WD Mud Terrain Tire': 17,
 'Golf TDI Diesel': 17,
 'Town Car': 17,
 'IS 250': 17,
 'Golf R': 17,
 'Silverado 4WD Mud Terrain Tire': 17,
 '525i': 17,
 'Outlander': 17,
 'Wrangler JL 4X4': 17,
 'Cooper S': 17,
 'Charger AWD': 17,
 'HR-V AWD': 17,
 'Civic Si': 16,
 'CX-5 4WD': 16,
 'Kona AWD': 16,
 '9-5 Turbo': 16,
 'Cherokee 4X4 Active Drive II': 16,
 'HR-V': 16,
 'Lanos': 16,
 'M4 Coupe': 16,
 '528i': 16,
 'Renegade 4X4': 16,
 'Cabrio': 16,
 'Range Rover 4X4': 16,
 '328i': 16,
 'Escalade 4WD': 16,
 '540i': 16,
 'Tahoe FFV': 16,
 'Fusion AWD': 16,
 'New Beetle TDI Diesel': 16,
 'TL': 16,
 'Ram 1500 Wagon': 16,
 'Corvette Z06': 16,
 'Tiguan 4MOTION': 16,
 'Aveo': 16,
 'Pacifica': 16,
 'Crown Victoria': 16,
 'Cougar': 16,
 'RX-8': 16,
 'IS 350 AWD': 16,
 'Grand Prix #': 16,
 '911 GT3': 16,
 '9-3 Convertible Turbo': 16,
 '9-3 SportCombi Turbo': 16,
 'Grand Cherokee 4X4 FFV': 16,
 'Ridgeline AWD': 16,
 'Yukon XL FFV': 16,
 'Yukon FFV': 16,
 'Suburban FFV': 16,
 'Z4 Roadster': 16,
 'Ion': 16,
 'Frontier V6': 16,
 '300 AWD FFV': 16,
 'Escape 4X4': 16,
 'E150 Van FFV': 16,
 'Verano': 16,
 'Tribute 4X4': 16,
 'SL #': 16,
 'Focus Wagon': 16,
 'Charger AWD FFV': 16,
 'SL': 16,
 'Spectra': 16,
 '1500 FFV': 16,
 'Ghost': 16,
 'S10 4X4': 16,
 'Vue AWD': 16,
 'Eos': 15,
 '911 Turbo S': 15,
 'Pathfinder 4WD': 15,
 'RAV4 AWD': 15,
 'Veloster': 15,
 'C1500 Tahoe': 15,
 'XT5 AWD': 15,
 'STS': 15,
 'S5': 15,
 'Enclave': 15,
 'Sonata Hybrid': 15,
 'Titan': 15,
 'IS 300': 15,
 'Bronco 4WD': 15,
 'Q50 AWD': 15,
 'Traverse': 15,
 'MKS AWD': 15,
 'C70 Convertible Turbo': 15,
 'Venza': 15,
 'Q5': 15,
 'Armada 4WD': 15,
 'Integra': 15,
 'GS 300': 15,
 'C1500 Suburban': 15,
 'E150 Wagon FFV': 14,
 'Taurus FFV AWD': 14,
 'Transit Connect Van FFV': 14,
 'Blazer': 14,
 'Transit Connect Wagon LWB FFV': 14,
 'Jetta TDI (modified)': 14,
 'S6': 14,
 'Veloster Turbo': 14,
 'Explorer FFV AWD': 14,
 'Trooper 4X4': 14,
 'RSX': 14,
 'Rodeo 4X4': 14,
 'Colorado ZR2 4WD': 14,
 'Grand Caravan AWD': 14,
 'A3 quattro': 14,
 'Stratus': 14,
 'Highlander AWD': 14,
 'Swift+': 14,
 'Mazda3 4-Door (SIL)': 14,
 'GX 460': 14,
 'Swift': 14,
 'Ram 1500 FFV': 14,
 'Continental GT Convertible': 14,
 '323i': 14,
 'Escape Hybrid': 14,
 'Jetta Wagon': 14,
 'Sebring FFV': 14,
 'LaCrosse': 14,
 'GT-R': 14,
 'X6 M': 14,
 'SL 550': 14,
 'Pilot': 14,
 'Envision AWD': 14,
 'Explorer Sport Trac 4X4': 14,
 'Passat 4MOTION': 14,
 'Gallardo Spyder': 14,
 'Windstar Wagon': 14,
 'FJ Cruiser 4WD': 14,
 'Juke': 14,
 'Phantom EWB': 14,
 'Escort': 14,
 'Lancer Evolution': 14,
 'MKX AWD': 14,
 '325Ci': 14,
 'G70 AWD': 14,
 'Vanden Plas': 14,
 '325Ci Convertible': 14,
 '325i': 14,
 'X1 xDrive28i': 14,
 '335i Cabriolet': 14,
 'Avalanche': 14,
 '328i Coupe': 14,
 'Sportage 4X4': 14,
 'Journey': 14,
 '328i Cabriolet': 14,
 'SW Wagon #': 14,
 'John Cooper Works 3 Door': 14,
 '330Ci': 14,
 '330i': 14,
 'Grand Vitara 4X4': 14,
 '200 FFV': 14,
 'Impreza 5-Door AWD': 14,
 '330Ci Convertible': 14,
 '335i Coupe': 14,
 'MKT AWD': 13,
 'RX 450h AWD': 13,
 'Century': 13,
 'CX-9 4WD': 13,
 'Camry Hybrid LE': 13,
 'F-TYPE Convertible': 13,
 'Cooper Countryman': 13,
 'Tracker Van 4X4': 13,
 'Grand Vitara': 13,
 'Sierra 4X4': 13,
 '911 Turbo S Cabriolet': 13,
 'ILX': 13,
 'Silverado 4X4': 13,
 'ES 300h': 13,
 'Lucerne': 13,
 'Transit Connect Van': 13,
 'Dart': 13,
 'ATS AWD': 13,
 'XJR #': 13,
 'Venza AWD': 13,
 'Navigator 4X4': 13,
 'Civic Hybrid': 13,
 'LX 570': 13,
 'Tundra 4X4': 13,
 '1500 4X4 eTorque': 13,
 '1500 eTorque': 13,
 'Nautilus AWD': 13,
 'Blazer AWD': 13,
 'Taurus AWD': 13,
 'Taurus #': 13,
 'Qashqai': 13,
 'A6': 13,
 'S-TYPE': 13,
 'S60 T5 Turbo': 13,
 'Flex AWD': 13,
 'Highlander Hybrid AWD': 13,
 'Z4 sDrive35i': 13,
 'Bronco Badlands 4WD': 13,
 'Element': 13,
 'GS 350 AWD': 13,
 'MKZ': 13,
 'Bronco Sasquatch 4WD': 13,
 'S 600': 13,
 'Galant': 13,
 'SL 600': 13,
 'M3 Sedan': 12,
 'Avenger FFV': 12,
 'LaCrosse AWD': 12,
 'Yukon Denali AWD': 12,
 'Taurus Wagon': 12,
 'CTS-V': 12,
 'SX4 Sedan Sport': 12,
 'Escape FFV': 12,
 'Town & Country FFV': 12,
 'GranTurismo': 12,
 'Express Cargo': 12,
 'XJ8': 12,
 '135i Coupe': 12,
 'John Cooper Works': 12,
 'G5': 12,
 'Savana Cargo': 12,
 'G20': 12,
 'Nitro 4X4': 12,
 'X5 M': 12,
 'Cayenne GTS': 12,
 'G 550': 12,
 'Panamera 4S': 12,
 'Gallardo': 12,
 'Xterra 4WD': 12,
 '128i Cabriolet': 12,
 'M6 Coupe': 12,
 '128i Coupe': 12,
 '135i Cabriolet': 12,
 'Colt': 12,
 'Beetle Convertible': 12,
 'F-150 Raptor 4X4': 12,
 'Explorer Sport Trac': 12,
 'CR-Z': 12,
 'Sorento 4X4': 12,
 'Sentra/200SX': 12,
 'Escalade ESV AWD': 12,
 'Bonneville': 12,
 'Blazer 4X4': 12,
 'Envoy 4X4': 12,
 'TrailBlazer 4X4': 12,
 'TrailBlazer': 12,
 'Prelude': 12,
 'Caravan FFV': 12,
 'Passat 4MOTION Wagon': 12,
 'Continental AWD': 12,
 'G15/G25 Savana Passenger': 12,
 '330xi': 12,
 '911 Carrera 4 GTS': 12,
 'Windstar Van': 12,
 'Impreza 4-Door AWD': 12,
 'Jimmy 4X4': 12,
 'Sonoma': 12,
 '325xi': 12,
 'Sierra 4WD AT4': 12,
 '1500 Classic': 12,
 '1500 Classic 4X4': 12,
 'CT4': 12,
 'G15/G25 Chevy Express': 12,
 'CT4 AWD': 12,
 'Echo': 12,
 'CT5': 12,
 'CT5 AWD': 12,
 '911 Carrera GTS Cabriolet': 12,
 '911 Carrera 4 GTS Cabriolet': 12,
 '911 Carrera GTS': 12,
 'M4 Cabriolet': 12,
 'Panamera': 12,
 'Panamera 4': 12,
 'tC': 12,
 '335i': 12,
 'Explorer FFV': 12,
 '9-3 Turbo': 12,
 'Q70 AWD': 12,
 'MX-6': 12,
 'S4 Cabriolet': 12,
 '612 Scaglietti': 12,
 'QX80 4WD': 12,
 'Esteem': 12,
 'F-TYPE Coupe': 12,
 'Renegade': 12,
 'E 320': 11,
 'C 300 4MATIC': 11,
 'GS 450h': 11,
 'SL 500': 11,
 'C70 Turbo': 11,
 'Continental GTC': 11,
 '760Li': 11,
 '550i': 11,
 'Millenia': 11,
 'G37 Coupe': 11,
 '9-7X AWD': 11,
 'STS AWD': 11,
 'Murano': 11,
 'X6 xDrive35i': 11,
 'M3 Coupe': 11,
 'Envoy': 11,
 'Wrangler Unlimited 4X4': 11,
 'Quattroporte': 11,
 'Accord Hybrid': 11,
 'Allure': 11,
 'CX-9': 11,
 'TL AWD': 11,
 'LeSabre': 11,
 'Fusion Hybrid': 11,
 'CC': 11,
 'K1500 Suburban 4X4': 11,
 '1500': 11,
 'Ghost EWB': 11,
 'DeVille': 11,
 'M6 Gran Coupe': 11,
 'Park Avenue #': 11,
 'QX50 AWD': 11,
 'QX60 AWD': 11,
 'Park Avenue': 11,
 'RC 350 AWD': 11,
 'RC F': 11,
 '1500 4X4': 11,
 '4Runner 4WD (Part-Time 4WD)': 11,
 'Trailblazer': 11,
 'CT6 AWD': 11,
 'Bentayga': 11,
 'F-150 (LT Tire Pkg)': 11,
 'Cooper Countryman ALL4': 11,
 'Sentra SR': 11,
 'Corolla Hatchback': 11,
 'XT6 AWD': 11,
 'Gladiator 4X4': 11,
 'Titan 4WD': 11,
 '9-5 Wagon Turbo': 11,
 'Flex': 11,
 'DB9': 11,
 'Journey AWD': 11,
 'Z4 sDrive30i': 11,
 '328i xDrive Touring': 11,
 'CL 600': 11,
 'IS 300 AWD': 10,
 'S8': 10,
 'A4 Cabriolet': 10,
 'Yukon XL 4WD FFV': 10,
 'C1500 Yukon FFV': 10,
 'C1500 Yukon XL FFV': 10,
 'Transit Connect Wagon LWB': 10,
 'RC 300 AWD': 10,
 'MX-5 (SIL)': 10,
 'C1500 Tahoe FFV': 10,
 'C1500 Suburban FFV': 10,
 'Yukon 4WD FFV': 10,
 'Expedition 4X4 FFV': 10,
 'F-150 FFV (Payload Pkg)': 10,
 'RAV4 Hybrid AWD': 10,
 'Tahoe 4WD FFV': 10,
 'Suburban 4WD FFV': 10,
 '335i xDrive Coupe': 10,
 'M3 Cabriolet': 10,
 'Macan S': 10,
 'Micra': 10,
 'Aurora': 10,
 'Achieva': 10,
 'Aerio': 10,
 'Truck': 10,
 '318i Convertible': 10,
 'allroad quattro': 10,
 'S60': 10,
 'S4 Avant': 10,
 '328i xDrive Coupe': 10,
 'Escort Wagon': 10,
 'Legacy Wagon AWD': 10,
 'Phantom Drophead Coupe': 10,
 'CT5-V': 10,
 'CT4-V': 10,
 'SW Wagon': 10,
 'RAV4 4WD': 10,
 'SC #': 10,
 '1.7EL': 10,
 'CX-30 4WD': 10,
 'Astro Passenger': 10,
 '718 Boxster': 10,
 '718 Boxster S': 10,
 '718 Cayman': 10,
 '718 Cayman S': 10,
 'F-150 FFV (LT Tire Pkg)': 10,
 'Atlas Cross Sport 4MOTION': 10,
 'John Cooper Works Clubman ALL4': 10,
 'Cooper S Clubman ALL4': 10,
 'M3 Convertible': 10,
 'SC': 10,
 'Thunderbird': 10,
 'Cherokee 4X4 Active Drive Lock': 10,
 'G90 AWD': 10,
 'GS 430': 10,
 'F-150 FFV 4X4 (LT Tire Pkg)': 10,
 'F-150 4X4 (LT Tire Pkg)': 10,
 'Bronco Black Diamond 4WD': 10,
 'Crossfire': 10,
 'X3': 10,
 'S40 2.4i': 10,
 'E 550 4MATIC': 10,
 'Z4 sDrive28i': 10,
 'xB': 10,
 'MKZ Hybrid': 10,
 'Optima Hybrid': 10,
 '650i Cabriolet': 10,
 'LS 460': 10,
 'Durango AWD FFV': 10,
 'Aveo 5': 10,
 'Cruze Eco': 10,
 'X5 xDrive50i': 10,
 'Mulsanne': 10,
 'Silverado 4X4 FFV': 10,
 'R8 Coupe': 10,
 'V8 Vantage S': 10,
 'XC60 T6 AWD': 10,
 'Dakota FFV': 10,
 'Golf Wagon': 10,
 'Q45': 10,
 'Golf Wagon TDI (modified)': 10,
 'Golf TDI (modified)': 10,
 'CTS Sport Wagon': 10,
 'Sierra 4X4 FFV': 10,
 'Sierra Denali AWD': 10,
 'Panamera Turbo': 10,
 'S15 Sonoma 4X4': 10,
 'CTS Sport Wagon AWD': 10,
 'Seville': 10,
 'B 200 Turbo': 10,
 'Town & Country AWD': 10,
 '500 Cabrio': 10,
 'Pacifica AWD': 10,
 'MKC AWD': 10,
 'F-150 4X4 FFV': 10,
 '318ti': 10,
 'Bronco Sport 4WD': 10,
 'Q60 AWD': 10,
 'T-150 Wagon FFV': 10,
 '500L': 10,
 'Magnum': 10,
 'GV80 AWD': 10,
 'MDX SH-AWD': 10,
 '1500 4X4 FFV': 10,
 'Probe': 10,
 'Xterra V6 4X4': 10,
 'Carrera 4 Cabriolet': 10,
 'S5 Cabriolet': 10,
 'Carrera 4S Cabriolet': 10,
 'Legacy 2.5i': 10,
 'Regal AWD': 10,
 'X3 xDrive30i': 10,
 'Seltos AWD': 10,
 'X6 xDrive50i': 10,
 '500 Hatchback': 10,
 'Grand Caravan FFV C/V': 10,
 'H3 4X4': 10,
 'IS 250 AWD': 10,
 'IS 350': 10,
 'E 300 4MATIC': 10,
 'Astro Cargo': 10,
 'MPV': 10,
 'S4 quattro': 10,
 'A6 Avant quattro': 10,
 'Safari Passenger': 10,
 '3.2TL': 10,
 'Safari Cargo': 10,
 'S2000': 10,
 'Taurus Wagon #': 10,
 'Breeze': 10,
 'XKR #': 10,
 'XKR Convertible #': 10,
 'XK8': 10,
 'Esteem Wagon': 10,
 'XK8 Convertible': 10,
 'Paseo': 10,
 'Mustang #': 9,
 'Ranger 4WD': 9,
 'E 350 4MATIC': 9,
 'X4 M40i': 9,
 '3.5RL': 9,
 'Grand Cherokee 4X4 (MDS)': 9,
 'NV200 Cargo Van': 9,
 'Hombre': 9,
 'F-150 4X4 (Payload Pkg)': 9,
 'F-150 (Payload Pkg)': 9,
 'FX35 AWD': 9,
 'Grand Cherokee L 4X4': 9,
 'Civic Coupe Si': 9,
 'Lumina': 9,
 'Venture': 9,
 'fortwo cabriolet': 9,
 'Cooper Clubman ALL4': 9,
 'Panamera GTS': 9,
 'CX-3': 9,
 '350Z Roadster': 9,
 'Aventador Coupe': 9,
 'Niro': 9,
 'Niro FE': 9,
 'Sequoia 4X4': 9,
 'Bonneville #': 9,
 'Encore': 9,
 'Encore AWD': 9,
 'Mustang (Performance Pkg)': 9,
 'S60 T6 AWD': 9,
 'Escape Hybrid AWD': 9,
 'ES 300': 9,
 'AMG GLC 43 4MATIC Coupe': 9,
 'Savana 1500 Cargo': 9,
 'LX 470': 9,
 'Phantom Coupe': 9,
 'TT Roadster': 9,
 'XT5': 9,
 'Discovery 4X4': 9,
 'GS 350': 9,
 '750i xDrive': 9,
 'X3 xDrive28i': 9,
 'B 200': 9,
 'Fiesta SFE': 9,
 '350Z': 9,
 'G1500/G2500 Chevy Express': 9,
 'SC 430': 9,
 'Envoy XL 4X4': 9,
 'Camry Solara Convertible': 9,
 '430i xDrive Coupe': 9,
 'Giulia': 9,
 'Giulia AWD': 9,
 'LS 460 L AWD': 9,
 'Venue': 9,
 'LS 460 AWD': 9,
 'F-250 4X4': 9,
 'Kona': 9,
 'Prius c': 9,
 'Truck 4X4': 9,
 'Legacy AWD Wagon': 9,
 'M240i xDrive Coupe': 9,
 'TLX SH-AWD': 9,
 'XLR': 9,
 'Corsair AWD': 9,
 'Express 1500 Cargo': 9,
 'S60 T5': 9,
 'G1500/G2500 Savana Passenger': 9,
 'TrailBlazer EXT 4X4': 9,
 'Genesis': 9,
 'A5 Cabriolet quattro': 9,
 'Insight': 9,
 'Charger AWD (MDS)': 9,
 'PT Turbo #': 9,
 'M240i Coupe': 8,
 'M240i Cabriolet': 8,
 'S60 R AWD Turbo': 8,
 'Eurovan': 8,
 'Dart Turbo Aero': 8,
 '430i xDrive Cabriolet': 8,
 'S60 2.5T AWD Turbo': 8,
 'V70 Wagon': 8,
 '124 Spider': 8,
 'John Cooper Works Clubman': 8,
 'S60 2.5T Turbo': 8,
 'Sonic RS': 8,
 'E 320 Wagon': 8,
 'Dart FFV': 8,
 'LS 600h L': 8,
 '440i Coupe': 8,
 'Caravan C/V': 8,
 'Sportage 4WD': 8,
 'Outback Sport AWD': 8,
 '440i xDrive Coupe': 8,
 'MDX AWD': 8,
 'Crossfire Roadster': 8,
 '650i Coupe': 8,
 'Optra': 8,
 'Stelvio AWD': 8,
 '240SX': 8,
 'Silverado XFE': 8,
 'Tahoe 4X4 FFV': 8,
 'Rainier AWD': 8,
 '335i xDrive': 8,
 '1.6EL': 8,
 'Jetta Wagon TDI Diesel': 8,
 'LS 500h AWD': 8,
 '750Li xDrive': 8,
 'LS 500 AWD': 8,
 'Nubira': 8,
 'LC 500h': 8,
 '328i Convertible': 8,
 'LC 500': 8,
 'Mazda2': 8,
 'Sorento 4WD': 8,
 'GranTurismo Convertible': 8,
 'X5 xDrive35d': 8,
 'Aerio Fastback': 8,
 'Ghibli': 8,
 'Civic Hatchback Sport': 8,
 'Navigator 4X4 FFV': 8,
 'Eldorado': 8,
 'Panamera 4S Executive': 8,
 'G37 Convertible': 8,
 'GLC 300 4MATIC Coupe': 8,
 '500 Abarth Cabrio': 8,
 'S15 Jimmy': 8,
 'G15 Express Passenger': 8,
 'Atlas 4MOTION': 8,
 'TrailBlazer EXT': 8,
 'A8 quattro': 8,
 'M6': 8,
 'xD': 8,
 '230i xDrive Coupe': 8,
 'T100 4X4': 8,
 'Envoy XL': 8,
 'G15 Savana Passenger': 8,
 '911 Targa 4 GTS': 8,
 'Kicks': 8,
 'Wraith': 8,
 'Macan': 8,
 'Ram 2500': 8,
 'Sierra XFE': 8,
 'T100': 8,
 'G35 Coupe': 8,
 '86': 8,
 'Ram 2500 4X4': 8,
 'Summit Wagon': 8,
 'PT Cruiser Convertible': 8,
 'Giulia Quadrifoglio': 8,
 '230i Coupe': 8,
 'XV Crosstrek AWD': 8,
 'Cooper Roadster': 8,
 'Continental Flying Spur': 8,
 'Focus Wagon #': 8,
 'Sonoma FFV': 8,
 'Cooper Coupe': 8,
 'SLK 250': 8,
 'Jetta GLX': 8,
 'GV70 AWD': 8,
 '500X AWD': 8,
 'F-150 FFV 4X4 (Payload Pkg)': 8,
 'RDX AWD': 8,
 'CLK 320': 8,
 'C 240': 8,
 'FR-S': 8,
 'GR86': 8,
 '200 Convertible': 8,
 '200 Convertible FFV': 8,
 'GL 550 4MATIC': 8,
 'M5 Sedan': 8,
 'F-150 FFV (Without Stop-Start)': 8,
 'K2500 4X4': 8,
 'Elantra N': 8,
 'Range Rover Evoque': 8,
 'Encore GX': 8,
 'CTS-V Sport Wagon': 8,
 'HHR Panel FFV': 8,
 'Cooper S Coupe': 8,
 'fortwo coupe': 8,
 'Impreza 2.5i': 8,
 'Cargo Van FFV': 8,
 'SX4 Sedan': 8,
 '9-3 Sport Sedan Turbo': 8,
 'Vitara Convertible 4X4': 8,
 'Boxster GTS': 8,
 'Cayman GTS': 8,
 'V70 T5 Turbo': 8,
 ...}

ðŸ”· The "Model" column should naturally be removed. Because the purpose of this model is to predict fuel consumption and CO2 emissions. These indicators are usually calculated, estimated and provided by the manufacturer for each vehicle based on its technical characteristics. As a result, predicting them is meaningless.

In [11]:
data.drop(columns=["Model"], inplace=True)

In [12]:
data

,Model year,Make,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km)
0,1995,Acura,Subcompact,1.8,4,A4,X,11.6,8.3,10.1,28,232
1,1995,Acura,Subcompact,1.8,4,M5,X,11.0,8.3,9.8,29,225
2,1995,Acura,Subcompact,1.8,4,M5,Z,10.8,8.3,9.7,29,223
3,1995,Acura,Compact,3.2,6,A4,Z,14.2,10.5,12.5,23,288
4,1995,Acura,Compact,3.2,6,A4,Z,14.6,11.0,13.0,22,299
...,...,...,...,...,...,...,...,...,...,...,...,...
28450,2025,Volvo,Station wagon: Small,2.0,4,AS8,Z,9.7,7.5,8.7,32,205
28451,2025,Volvo,Station wagon: Mid-size,2.0,4,AS8,Z,10.7,8.1,9.5,30,223
28452,2025,Volvo,Sport utility vehicle: Small,2.0,4,AS8,Z,10.1,7.8,9.1,31,213
28453,2025,Volvo,Sport utility vehicle: Small,2.0,4,AS8,Z,10.0,7.8,9.0,31,212
28454,2025,Volvo,Sport utility vehicle: Standard,2.0,4,AS8,Z,11.5,9.0,10.4,27,244

In [13]:
data["Vehicle class"].value_counts().to_dict()

{'Compact': 3887,
 'Mid-size': 3660,
 'Sport utility vehicle': 3044,
 'Pickup truck: Standard': 3035,
 'Subcompact': 2706,
 'Sport utility vehicle: Small': 2328,
 'Full-size': 1790,
 'Sport utility vehicle: Standard': 1550,
 'Two-seater': 1542,
 'Minicompact': 1155,
 'Station wagon: Small': 1005,
 'Pickup truck: Small': 621,
 'Minivan': 618,
 'Station wagon: Mid-size': 528,
 'Van: Cargo': 469,
 'Van: Passenger': 398,
 'Special purpose vehicle': 119}

In [14]:
sorted(data["Vehicle class"].value_counts().to_dict())

['Compact',
 'Full-size',
 'Mid-size',
 'Minicompact',
 'Minivan',
 'Pickup truck: Small',
 'Pickup truck: Standard',
 'Special purpose vehicle',
 'Sport utility vehicle',
 'Sport utility vehicle: Small',
 'Sport utility vehicle: Standard',
 'Station wagon: Mid-size',
 'Station wagon: Small',
 'Subcompact',
 'Two-seater',
 'Van: Cargo',
 'Van: Passenger']

ðŸ”· For simplifying the model, we change the values of "Vehicle class" in this way:

In [15]:
data.loc[data["Vehicle class"].isin(["Pickup truck: Small","Pickup truck: Standard"]), "Vehicle class" ] = "Pickup truck"

data.loc[data["Vehicle class"].isin(["Sport utility vehicle: Small","Sport utility vehicle: Standard"]), "Vehicle class" ] = "Sport utility vehicle"

data.loc[data["Vehicle class"].isin(["Station wagon: Mid-size","Station wagon: Small"]), "Vehicle class" ] = "Station wagon"

data.loc[data["Vehicle class"].isin(["Van: Cargo","Van: Passenger"]), "Vehicle class" ] = "Van"

In [16]:
data

,Model year,Make,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km)
0,1995,Acura,Subcompact,1.8,4,A4,X,11.6,8.3,10.1,28,232
1,1995,Acura,Subcompact,1.8,4,M5,X,11.0,8.3,9.8,29,225
2,1995,Acura,Subcompact,1.8,4,M5,Z,10.8,8.3,9.7,29,223
3,1995,Acura,Compact,3.2,6,A4,Z,14.2,10.5,12.5,23,288
4,1995,Acura,Compact,3.2,6,A4,Z,14.6,11.0,13.0,22,299
...,...,...,...,...,...,...,...,...,...,...,...,...
28450,2025,Volvo,Station wagon,2.0,4,AS8,Z,9.7,7.5,8.7,32,205
28451,2025,Volvo,Station wagon,2.0,4,AS8,Z,10.7,8.1,9.5,30,223
28452,2025,Volvo,Sport utility vehicle,2.0,4,AS8,Z,10.1,7.8,9.1,31,213
28453,2025,Volvo,Sport utility vehicle,2.0,4,AS8,Z,10.0,7.8,9.0,31,212
28454,2025,Volvo,Sport utility vehicle,2.0,4,AS8,Z,11.5,9.0,10.4,27,244

In [17]:
data["Vehicle class"].value_counts().to_dict()

{'Sport utility vehicle': 6922,
 'Compact': 3887,
 'Mid-size': 3660,
 'Pickup truck': 3656,
 'Subcompact': 2706,
 'Full-size': 1790,
 'Two-seater': 1542,
 'Station wagon': 1533,
 'Minicompact': 1155,
 'Van': 867,
 'Minivan': 618,
 'Special purpose vehicle': 119}

In [18]:
sorted(data["Vehicle class"].value_counts().to_dict())

['Compact',
 'Full-size',
 'Mid-size',
 'Minicompact',
 'Minivan',
 'Pickup truck',
 'Special purpose vehicle',
 'Sport utility vehicle',
 'Station wagon',
 'Subcompact',
 'Two-seater',
 'Van']

Sedans: Minicompact, Subcompact, Compact, Mid-size, Full-size

Station Wagons: Station wagon

Trucks: Pickup truck, Van, Minivan, Sport utility vehicle, Special purpose vehicle

Two Seaters: Two-seater

In [19]:
data[["Engine size (L)"]].describe()

       Engine size (L)
count     28455.000000
mean          3.331731
std           1.339365
min           0.800000
25%           2.200000
50%           3.000000
75%           4.200000
max           8.400000

ðŸ”· The column "Engine size" has no problem...

In [20]:
data["Cylinders"].value_counts().to_dict()

{4: 10377, 6: 10091, 8: 6410, 5: 592, 12: 535, 3: 232, 10: 184, 2: 17, 16: 17}

In [21]:
data[["Cylinders"]].describe()

          Cylinders
count  28455.000000
mean       5.818169
std        1.808495
min        2.000000
25%        4.000000
50%        6.000000
75%        8.000000
max       16.000000

ðŸ”· The column "Cylinders" has no problem...

In [22]:
data["Transmission"].value_counts().to_dict()

{'A4': 5489,
 'M5': 3223,
 'AS6': 2934,
 'M6': 2832,
 'AS8': 2361,
 'A6': 1977,
 'A5': 1604,
 'A8': 1041,
 'AV': 943,
 'AS5': 874,
 'AM7': 841,
 'A9': 699,
 'AS7': 621,
 'AS10': 567,
 'A10': 324,
 'A7': 281,
 'AM8': 260,
 'AS4': 258,
 'AM6': 240,
 'A3': 187,
 'AS9': 182,
 'AV6': 171,
 'AV7': 159,
 'M7': 154,
 'AV8': 145,
 'AV10': 45,
 'AV1': 28,
 'AM9': 6,
 'AM5': 6,
 'M4': 3}

ðŸ”· In 895 samples, "AV" is setted for "Transmission" column. Its not completely clear. should be removed.

In [23]:
data.drop(index=list(data.loc[data["Transmission"] == "AV"].index), inplace=True)
data.reset_index(inplace=True)
data.drop(columns=["index"], inplace=True)

In [24]:
data

,Model year,Make,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km)
0,1995,Acura,Subcompact,1.8,4,A4,X,11.6,8.3,10.1,28,232
1,1995,Acura,Subcompact,1.8,4,M5,X,11.0,8.3,9.8,29,225
2,1995,Acura,Subcompact,1.8,4,M5,Z,10.8,8.3,9.7,29,223
3,1995,Acura,Compact,3.2,6,A4,Z,14.2,10.5,12.5,23,288
4,1995,Acura,Compact,3.2,6,A4,Z,14.6,11.0,13.0,22,299
...,...,...,...,...,...,...,...,...,...,...,...,...
27507,2025,Volvo,Station wagon,2.0,4,AS8,Z,9.7,7.5,8.7,32,205
27508,2025,Volvo,Station wagon,2.0,4,AS8,Z,10.7,8.1,9.5,30,223
27509,2025,Volvo,Sport utility vehicle,2.0,4,AS8,Z,10.1,7.8,9.1,31,213
27510,2025,Volvo,Sport utility vehicle,2.0,4,AS8,Z,10.0,7.8,9.0,31,212
27511,2025,Volvo,Sport utility vehicle,2.0,4,AS8,Z,11.5,9.0,10.4,27,244

ðŸ”· Separating transmission type and number of gears.

In [25]:
Number_Of_Gears = []
NOG = ""

for index,value in zip(list(data["Transmission"].keys()), list(data["Transmission"].values)):
    
    for i in value:
        if i.isnumeric() == True:
            NOG = NOG + i
            
    Number_Of_Gears.append(int(NOG))
    data.loc[index, "Transmission"] = value[:-len(NOG)]
    NOG = ""
    
data.insert(6, "Number of gears", Number_Of_Gears)

In [26]:
data

,Model year,Make,Vehicle class,Engine size (L),Cylinders,Transmission,Number of gears,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km)
0,1995,Acura,Subcompact,1.8,4,A,4,X,11.6,8.3,10.1,28,232
1,1995,Acura,Subcompact,1.8,4,M,5,X,11.0,8.3,9.8,29,225
2,1995,Acura,Subcompact,1.8,4,M,5,Z,10.8,8.3,9.7,29,223
3,1995,Acura,Compact,3.2,6,A,4,Z,14.2,10.5,12.5,23,288
4,1995,Acura,Compact,3.2,6,A,4,Z,14.6,11.0,13.0,22,299
...,...,...,...,...,...,...,...,...,...,...,...,...,...
27507,2025,Volvo,Station wagon,2.0,4,AS,8,Z,9.7,7.5,8.7,32,205
27508,2025,Volvo,Station wagon,2.0,4,AS,8,Z,10.7,8.1,9.5,30,223
27509,2025,Volvo,Sport utility vehicle,2.0,4,AS,8,Z,10.1,7.8,9.1,31,213
27510,2025,Volvo,Sport utility vehicle,2.0,4,AS,8,Z,10.0,7.8,9.0,31,212
27511,2025,Volvo,Sport utility vehicle,2.0,4,AS,8,Z,11.5,9.0,10.4,27,244

In [27]:
data["Fuel type"].value_counts()

Fuel type
X    14630
Z    11235
E     1100
D      508
N       39
Name: count, dtype: int64

ðŸ”· According to the dataset description, we change the "fuel type" column.

In [28]:
data.loc[data["Fuel type"] == "X", "Fuel type"] = "Regular gasoline"

data.loc[data["Fuel type"] == "Z", "Fuel type"] = "Premium gasoline"

data.loc[data["Fuel type"] == "D", "Fuel type"] = "Diesel"

data.loc[data["Fuel type"] == "E", "Fuel type"] = "Ethanol (E85)"

data.loc[data["Fuel type"] == "N", "Fuel type"] = "Natural Gas"

In [29]:
data

,Model year,Make,Vehicle class,Engine size (L),Cylinders,Transmission,Number of gears,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km)
0,1995,Acura,Subcompact,1.8,4,A,4,Regular gasoline,11.6,8.3,10.1,28,232
1,1995,Acura,Subcompact,1.8,4,M,5,Regular gasoline,11.0,8.3,9.8,29,225
2,1995,Acura,Subcompact,1.8,4,M,5,Premium gasoline,10.8,8.3,9.7,29,223
3,1995,Acura,Compact,3.2,6,A,4,Premium gasoline,14.2,10.5,12.5,23,288
4,1995,Acura,Compact,3.2,6,A,4,Premium gasoline,14.6,11.0,13.0,22,299
...,...,...,...,...,...,...,...,...,...,...,...,...,...
27507,2025,Volvo,Station wagon,2.0,4,AS,8,Premium gasoline,9.7,7.5,8.7,32,205
27508,2025,Volvo,Station wagon,2.0,4,AS,8,Premium gasoline,10.7,8.1,9.5,30,223
27509,2025,Volvo,Sport utility vehicle,2.0,4,AS,8,Premium gasoline,10.1,7.8,9.1,31,213
27510,2025,Volvo,Sport utility vehicle,2.0,4,AS,8,Premium gasoline,10.0,7.8,9.0,31,212
27511,2025,Volvo,Sport utility vehicle,2.0,4,AS,8,Premium gasoline,11.5,9.0,10.4,27,244

In [30]:
data["City (L/100 km)"].describe()

count    27512.000000
mean        13.934251
std          3.661299
min          4.000000
25%         11.400000
50%         13.500000
75%         16.000000
max         33.300000
Name: City (L/100 km), dtype: float64

ðŸ”· The column "City (L/100 km)" has no problem...

In [31]:
data["Highway (L/100 km)"].describe()

count    27512.000000
mean        10.064634
std          2.560566
min          3.900000
25%          8.300000
50%          9.600000
75%         11.400000
max         22.100000
Name: Highway (L/100 km), dtype: float64

ðŸ”· The column "Highway (L/100 km)" has no problem...

In [32]:
data["Combined (L/100 km)"].describe()

count    27512.000000
mean        12.193010
std          3.128259
min          4.000000
25%         10.000000
50%         11.700000
75%         13.900000
max         27.500000
Name: Combined (L/100 km), dtype: float64

ðŸ”· The column "Combined (L/100 km)" has no problem...

ðŸ”· The column "Combined (mpg)" is no needed. should be removed.

In [33]:
data.drop(columns=["Combined (mpg)"], inplace=True)

In [34]:
data

,Model year,Make,Vehicle class,Engine size (L),Cylinders,Transmission,Number of gears,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),CO2 emissions (g/km)
0,1995,Acura,Subcompact,1.8,4,A,4,Regular gasoline,11.6,8.3,10.1,232
1,1995,Acura,Subcompact,1.8,4,M,5,Regular gasoline,11.0,8.3,9.8,225
2,1995,Acura,Subcompact,1.8,4,M,5,Premium gasoline,10.8,8.3,9.7,223
3,1995,Acura,Compact,3.2,6,A,4,Premium gasoline,14.2,10.5,12.5,288
4,1995,Acura,Compact,3.2,6,A,4,Premium gasoline,14.6,11.0,13.0,299
...,...,...,...,...,...,...,...,...,...,...,...,...
27507,2025,Volvo,Station wagon,2.0,4,AS,8,Premium gasoline,9.7,7.5,8.7,205
27508,2025,Volvo,Station wagon,2.0,4,AS,8,Premium gasoline,10.7,8.1,9.5,223
27509,2025,Volvo,Sport utility vehicle,2.0,4,AS,8,Premium gasoline,10.1,7.8,9.1,213
27510,2025,Volvo,Sport utility vehicle,2.0,4,AS,8,Premium gasoline,10.0,7.8,9.0,212
27511,2025,Volvo,Sport utility vehicle,2.0,4,AS,8,Premium gasoline,11.5,9.0,10.4,244

In [35]:
data["CO2 emissions (g/km)"].describe()

count    27512.000000
mean       277.505125
std         64.587975
min         94.000000
25%        232.000000
50%        269.000000
75%        315.000000
max        633.000000
Name: CO2 emissions (g/km), dtype: float64

ðŸ”· The column "CO2 emissions (g/km)" has no problem...

### ðŸŸ¦ Saving Data

In [36]:
data.to_csv(path_or_buf=os.path.basename("data-cleaned.csv"), sep=",", index=False, encoding="utf-8")